### ISSUE TITLE
z-index Property doesn't work correctly 

### ISSUE THREAD

**Issue by horvan** [radixtheme/radix#11]
Dear radix developers I don't know if this is Drupal related or it is fixable in your theme though. 

I have a new div with the id trunme in ../system/html.tpl.php
```html
....
</head>
<body class="<?php print $classes; ?>" <?php print $attributes;?>>
<div id="turnme">
  <div id="skip-link">
    <a href="#main" class="element-invisible element-focusable"><?php print t('Skip to main content'); ?></a>
  </div>
  <?php print $page_top; ?>
  <?php print $page; ?>
  <?php print $page_bottom; ?>
</div>
</body>
</html>
```

The corresponding style is
```css
// Styles for main layout
// --------------------------------------------------

@media only screen and (max-width: 479px) {
  #turnme {
    display: run-in !important;
position:static;
background-image: url(../images/mobile-direction.jpg);
background-size: 100% 100%;
background-repeat: repeat;
max-width: auto;
min-height:auto;
z-index:99999 ;
  }
}
```
The result looks like this:

![screenshot](https://cloud.githubusercontent.com/assets/5676367/10563234/fc3b85d2-7581-11e5-8171-b60fabbd85b6.png)

but it should look more like this:

![mobile-direction](https://cloud.githubusercontent.com/assets/5676367/10563239/2688e618-7582-11e5-8d89-790747ef55ff.jpg)

I am not shure if this is a radix bug or a bug in drupal itself but I like to mention it iand hope you are a bit more wise than me!

I am looking forward to hear from you.

Thanks in advance

@horvan
